# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'Anyfleet2310' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # 网络请求
  pod 'Alamofire', '5.4.3'
  # JSON数据转化
  pod 'HandyJSON', '5.0.2'
  # 键盘弹出、回缩
  pod 'IQKeyboardManagerSwift', '6.5.6'
  # 缓存网络图片
  pod 'Kingfisher', '6.3.0'
  # Loading
  pod 'JGProgressHUD', '2.2'
  # Images
  pod 'ZLPhotoBrowser', '4.3.9'
  # MQTT
  pod 'CocoaMQTT', '2.1.3'
  # 谷歌地图
  pod 'GoogleMaps', '7.4.0'
  pod 'Google-Maps-iOS-Utils', '4.1.0'
  # 下拉刷新
  pod 'MJRefresh', '3.7.5'
  # 无数据显示
  pod 'EmptyDataSet-Swift', '5.0.0'
  # 钥匙串
  pod 'KeychainAccess', '4.2.2'
  
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
