# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'MJDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for MJDemo
  
  # 网络请求
  pod 'Alamofire', '5.4.3'
  # 键盘弹出、回缩
  pod 'IQKeyboardManagerSwift', '6.5.6'
  # 缓存网络图片
  pod 'Kingfisher', '6.3.0'
  # 下拉刷新
  pod 'MJRefresh', '3.7.5'
  # 无数据显示
  pod 'EmptyDataSet-Swift', '5.0.0'
  # Loading
  pod 'JGProgressHUD', '2.2'
  
#  post_install do |installer|
#    installer.pods_project.build_configurations.each do |config|
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#    end
  
end
